### PR TITLE
turn camera off after unmount

### PR DESCRIPTION
**Pull request by wildskyf**
ref #112

### CODE REVIEW

**Comment by JodusNodus** [comment]
Thanks for the PR, Looks good. i'll test it out later.

**Comment by wildskyf** [comment]
I guess you mean we should set it to `false`?

I thought it is no need to.
Component will construct with the right value, `false`, when it is called again.

**Comment by wildskyf** [comment]
You could set it to `false` if you want. But I don't think it is necessary.

**Comment by wildskyf** [comment]
@JodusNodus How is the progress of this pull request?

**Comment by wildskyf** [comment]
@JodusNodus How is the progress of this pull request?

**Pull request closed without merging**
