### PR TITLE
Support React 17

### PR DESCRIPTION
**Pull request by Tobiaqs**
React 17 has been released. I've tested this library on React 17 and I'm not noticing any issues.

Not asking for this to be merged right away, but it might be worth looking into whether the React dependencies can be safely increased to 17.

### CODE REVIEW

**Comment by jperelli** [comment]
I installed in react v17 using this PR with following command:
```
npm install JodusNodus/react-qr-reader#pull/192/head
```

**Comment by luizhfff** [comment]
Is this going to be merged anytime soon? Thanks

**Comment by chaitanyaarige** [comment]
@Tobiaqs please request to merge as I am getting error on package installation

**Comment by chaitanyaarige** [comment]
Thanks a lot

**Pull request merged**
